# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{eita-jrails}
  s.version = "0.9.2"

  s.authors = ["Aaron Eisenberger", "Patrick Hurley", "Brent Miller", "Braulio Bhavamitra"]
  s.date = %q{2014-10-06}
  s.default_executable = %q{jrails}
  s.summary = %q{jRails is a drop-in jQuery replacement for the prototope-rails gem.}
  s.description = %q{Using jRails, you can still use RJS and Jquery/JqueryUi helpers with the same API as Prototype/Scryptaculous helpers.}
  s.email = %q{braulio@eita.org.br}
  s.homepage = %q{http://github.com/coletivoEITA/jrails}
  s.executables = ["jrails"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "bin/jrails",
  ] + Dir.glob('{assets,lib}/**/*')

  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{jrails}
  s.rubygems_version = %q{1.3.7}
  s.specification_version = 3
end

